name: my_journal
description: A new Flutter project.

publish_to: "none"

version: 3.0.0+11

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cloud_firestore: ^4.0.4
  cupertino_icons: ^1.0.2
  dynamic_color: ^1.5.4
  encrypt: ^5.0.1
  equatable: ^2.0.3
  eva_icons_flutter: ^3.1.0
  firebase_auth: ^4.1.1
  firebase_core: ^2.1.1
  flutter:
    sdk: flutter
  flutter_quill: ^6.1.2
  flutter_svg: ^1.0.3
  google_sign_in: ^5.2.4
  intl: ^0.17.0
  provider: ^6.0.2
  shared_preferences: ^2.0.15
  tuple: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
