name: my_journal
description: A new Flutter project.

publish_to: "none"

version: 2.0.1+6

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.10
  cupertino_icons: ^1.0.2
  encrypt: ^5.0.1
  equatable: ^2.0.3
  eva_icons_flutter: ^3.1.0
  firebase_auth: ^3.3.10
  firebase_core: ^1.13.1
  flutter:
    sdk: flutter
  flutter_quill: ^5.0.3
  flutter_svg: ^1.0.3
  google_sign_in: ^5.2.4
  intl: ^0.17.0
  provider: ^6.0.2
  shared_preferences: ^2.0.15
  tuple: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
